### ISSUE TITLE
Crash bug when operating with bag data

### ISSUE THREAD

**Issue by evenator** [evenator/CarND-Capstone#9]
Reported by @alanswx on Slack:

> FYI - right now we have a crash bug when we play back the rosbag - i forget whether it is in the waypoint updater or dbw

**Comment by alanswx** [comment]
```
[ERROR] [1505575508.467092]: bad callback: <bound method WaypointUpdater.waypoints_cb of <__main__.WaypointUpdater object at 0x7fca39b61f10>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/nisn/CarND-Capstone-lucas-dev/ros/src/waypoint_updater/waypoint_updater.py", line 83, in waypoints_cb
    lane.waypoints.append(self.curr_waypoints[idx])
IndexError: list index out of range
```

**Comment by evenator** [comment]
Ok, I see what's going on here. It should be an easy fix.

**Comment by evenator** [comment]
I was able to reproduce the problem on `lucas-dev` and fix the problem with the changes in `9-fix-crash-bug`.
